site_name: Scipy 2020 Poster on Quasi-orthonormal Encoding for Machine Learning Applications

# the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math)

theme:
    name: mkdocs
    custom_dir: ../../poster_theme
        
markdown_extensions:
  - mdx_math:
       enable_dollar_delimiter: True #for use of inline $..$
  - fenced_code
  - codehilite
  - footnotes

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

